jobs:
  images:
    env:
      REGISTRY: 436866023604.dkr.ecr.eu-central-1.amazonaws.com
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Cache local Gradle dependencies
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-shared-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      env:
        CI: false
        GENERATE_SOURCEMAP: false
      name: Build the image without tests
      run: ./gradlew jibDockerBuild -x test --no-daemon --image opendatadiscovery/${{
        github.event.repository.name }} --scan -Pversion=cve
    - continue-on-error: true
      uses: aquasecurity/trivy-action@0.11.2
      with:
        exit-code: '1'
        format: table
        image-ref: opendatadiscovery/odd-platform:cve
name: CVE checks monthly
on:
  repository_dispatch:
    types: trigger-ga___cve.yaml
