concurrency: main_build
jobs:
  images:
    env:
      REGISTRY: 436866023604.dkr.ecr.eu-central-1.amazonaws.com
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - continue-on-error: true
      uses: unfor19/install-aws-cli-action@v1
    - continue-on-error: true
      name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: ${{ secrets.AWS_REGION }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - continue-on-error: true
      name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1.3.3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Cache local Gradle dependencies
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-shared-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      env:
        CI: false
        GENERATE_SOURCEMAP: false
      name: Run tests and build the image
      run: ./gradlew test jib --no-daemon --image ${{ env.REGISTRY }}/${{ github.event.repository.name
        }} --scan -Pversion=ci-${GITHUB_SHA::6}
  update_tag:
    needs:
    - images
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: development
        repository: opendatadiscovery/saas-iac
        token: ${{ secrets.ODD_GIT_TOKEN }}
    - continue-on-error: true
      run: 'sed -i "s/tag:.*/tag: ci-${GITHUB_SHA::6}/" states/main/eu-central-1/development/argocd/odd-platform/demo.yaml

        git config user.name github-actions

        git config user.email github-actions@github.com

        git add .

        git commit --allow-empty -m "update tag"

        git push'
name: Main branch Build
on:
  repository_dispatch:
    types: trigger-ga___main-build.yaml
