jobs:
  update_release_draft:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: release-drafter/release-drafter@v5
      with:
        config-name: release-drafter.yaml
        disable-autolabeler: false
name: Release Drafter
on:
  repository_dispatch:
    types: trigger-ga___release-drafter.yaml
