concurrency:
  cancel-in-progress: true
  group: pr-cg-${{ github.ref }}
jobs:
  run_playwright_tests:
    uses: ./.github/workflows/run-playwright-tests.yml
  run_tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Cache local Gradle dependencies
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Cache local npm dependencies
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        path: ~/.npm
        restore-keys: '${{ runner.os }}-node-

          '
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      env:
        CI: false
        GENERATE_SOURCEMAP: false
      name: Build and run tests
      run: ./gradlew odd-platform-api:build ${{ github.event.inputs.buildOptions }}
        --no-daemon --scan -PbundleUI=false
    - continue-on-error: true
      if: always()
      name: Publish test reports
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        check_name: Test Results
        comment_mode: create new
        files: odd-platform-api/build/test-results/**/*.xml
name: Run tests
on:
  repository_dispatch:
    types: trigger-ga___run-pr-tests.yaml
permissions:
  checks: write
  pull-requests: write
