jobs:
  format-check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - continue-on-error: true
      name: Install dependencies
      run: 'cd tests

        npm ci

        '
    - continue-on-error: true
      name: Check formatting
      run: 'cd tests

        npm run format:check

        '
    timeout-minutes: 60
  lint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - continue-on-error: true
      name: Install dependencies
      run: 'cd tests

        npm ci

        '
    - continue-on-error: true
      name: Run linter
      run: 'cd tests

        npm run lint:ci

        '
    timeout-minutes: 60
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Build docker container
      run: ./gradlew jibDockerBuild -x test -x checkstyleMain -x checkstyleTest --image
        odd-platform:e2e-latest-build
    - continue-on-error: true
      name: Start containers
      run: 'cd tests

        npm run odd-up

        '
    - continue-on-error: true
      name: Install dependencies
      run: 'cd tests

        npm ci

        '
    - continue-on-error: true
      name: Install Playwright Browsers
      run: 'cd tests

        npx playwright install --with-deps chromium

        '
    - continue-on-error: true
      name: Run Playwright tests
      run: 'cd tests

        npm run test:ci

        '
    - continue-on-error: true
      if: always()
      name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: tests/playwright-report/
        retention-days: 10
    timeout-minutes: 60
name: Playwright Tests
on:
  repository_dispatch:
    types: trigger-ga___run-playwright-tests.yml
