jobs:
  sonar-backend:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - continue-on-error: true
      uses: unfor19/install-aws-cli-action@v1
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      name: Gradle cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-shared-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Node cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-shared-node-${{ hashFiles('**/package-lock.json') }}
        path: odd-platform-ui/.npm
        restore-keys: '${{ runner.os }}-node-

          '
    - continue-on-error: true
      env:
        BASE_REF: ${{ github.base_ref }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HEAD_REF: ${{ github.head_ref }}
        JAVA_OPTS: -Xms2048m -Xmx2048m
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: ${{ github.event_name == 'pull_request_target' }}
      name: Build and analyze pull request target
      run: "./gradlew -x compileTestJava :odd-platform-api:sonarqube \\\n  --info\
        \ \\\n  --no-daemon \\\n  --scan \\\n  -PbundleUI=false \\\n  -Dsonar.pullrequest.key=${{\
        \ github.event.pull_request.number }} \\\n  -Dsonar.pullrequest.branch=$HEAD_REF\
        \ \\\n  -Dsonar.pullrequest.base=$BASE_REF\n"
    - continue-on-error: true
      env:
        CI: false
        GENERATE_SOURCEMAP: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JAVA_OPTS: -Xms2048m -Xmx2048m
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: ${{ github.event_name == 'push' }}
      name: Build main branch
      run: "./gradlew -x compileTestJava :odd-platform-api:sonarqube \\\n  --info\
        \ \\\n  --no-daemon \\\n  --scan \\\n  -PbundleUI=false"
name: SonarCloud Scan [backend]
on:
  repository_dispatch:
    types: trigger-ga___sonar-backend.yaml
